stages:
  - build
  - test

build:
  image: gcc
  stage: build
  script:
    - make
  artifacts:
    paths:
      - bin
      - asm
      - corewar
      - champions

norm:
  stage: test
  image: adrienbrignon/epitech-c
  allow_failure: yes
  script:
    - normez -u

test:
  stage: test
  image: adrienbrignon/epitech-c
  script:
    - bin/test
